#!/bin/bash



# -------------------------------------------------------

# print_help:
# Print usage for pwd_b
print_help () {
	echo "Usage : pwd [option]"
    echo "  example:   pwd -d "
    echo "  example:   pwd -h"
    echo "\n\t-d\tdebug mode"
    echo "\t-h\tdisplay this help and exit"
	exit 0
}

# check_arguments:
# Check argument in parameter
# -h for print help
# -d to enable debug
check_arguments () {
	case $1 in
		--help|-h)
			print_help
			;;
		-d)
			Debug="true"
			;;
	esac
}

# echod:
# Enable echo for debug
echod () {
    if [ "$Debug" = "true" ]
    then
        echo "$*"
    fi
}

# -------------------------------------------------------

# check_main_directory:
# determine if the main directory is / (root) or ~ (home)
check_main_directory () {
	case "$PWD" in 
		"$HOME"*)
			return 1
			;;
		"/"*)
			return 2
			;;
	esac
}

checkFirstDir ()  {
    FirstDirectory=${ArrayDirectory[0]}
    echod "First dir : $FirstDirectory"
    if [ "$FirstDirectory" = "" ]
    then
        Way=""
    else
        if [ "$Slash" = "/" ]
        then
            Way="$FirstDirectory"
        else
            Way="/$FirstDirectory"
        fi        
    fi
}

# checkDirectory:
# 1st pass of compression
# take the first word after space ' '
checkDirectory () {
    echod "->             '$DirectoryName'"
    CompressDirectoryName=$(tr -d ' ' <<< "$DirectoryName")
    echod "-> compressed: '$CompressDirectoryName'"
}

formatDirectoryName () {
    echod "-> $CompressDirectoryName"
    if [ "${#CompressDirectoryName}" -ge 12 ]
    then
        DirectoryNameFormated="${CompressDirectoryName:0:4}."
    elif [ "${#CompressDirectoryName}" -ge 6 ]
    then
        DirectoryNameFormated="${CompressDirectoryName:0:3}."
    else
        DirectoryNameFormated="${CompressDirectoryName}"
    fi
}



#-------- Main program ----------
Debug="false"

Slash=""
AbsolutePath=""
Way=""
DirectoriesList=""
ArrayDirectory=""
CompressDirectoryName=""
DirectoryNameFormated=""

check_arguments "$1"

## ------------ ##
## Main Program ##
## ------------ ##

check_main_directory

if [ $? -eq 1 ]
then
	Slash="~"
	AbsolutePath="${PWD:${#HOME}+1}/" #delete 'home/$USER/'
else	#equal 2
	Slash="/"
 	AbsolutePath="$PWD/"
fi
echod "Absolute path: $AbsolutePath"

#creation du chemin a afficher
DirectoriesList=$(tr '/' '\n' <<< "$AbsolutePath")
echod "$DirectoriesList"

OldIFS=$IFS
IFS=$'\n'

ArrayDirectory=($DirectoriesList)
echod "${ArrayDirectory[@]}"

checkFirstDir

for DirectoryName in "${ArrayDirectory[@]:1}"
do
    checkDirectory
    formatDirectoryName 
    Way+="/$DirectoryNameFormated"
done

IFS=$OldIFS

echo "$Slash$Way"