#!/bin/bash

#determine if pwd is / (root) or ~ (home)
checkSlash () {
	case "$PWD" in 
		"$HOME"*)
			return 1
			;;
		"/"*)
			return 2
			;;
	esac
}

checkFirstDir ()  {
    FirstDirectory=${ArrayDirectory[0]}
    echod "First dir : $FirstDirectory"
    if [ "$FirstDirectory" = "" ]
    then
        Way=""
    else
        if [ "$Slash" = "/" ]
        then
            Way="$FirstDirectory"
        else
            Way="/$FirstDirectory"
        fi        
    fi
}

# checkDirectory:
# 1st pass of compression
# take the first word after space ' '
checkDirectory () {
    echod "-> '$DirectoryName'"
    CompressDirectoryName=$(tr -d ' ' <<< "$DirectoryName")
    echod "-> compressed: '$CompressDirectoryName'"
}

formatDirectoryName () {
    echod "-> $CompressDirectoryName"
    if [ "${#CompressDirectoryName}" -ge 12 ]
    then
        DirectoryNameFormated="${CompressDirectoryName:0:4}."
    elif [ "${#CompressDirectoryName}" -ge 6 ]
    then
        DirectoryNameFormated="${CompressDirectoryName:0:3}."
    else
        DirectoryNameFormated="${CompressDirectoryName}"
    fi
}

echod () {
    if [ "$Debug" = "true" ]
    then
        echo "$*"
    fi
}

#-------- Main program ----------
Debug="false"

Slash=""
AbsolutePath=""
Way=""
DirectoriesList=""
ArrayDirectory=""
CompressDirectoryName=""
DirectoryNameFormated=""

if [ "$1" = "-d" ]
then
    Debug="true"
fi

checkSlash

if [ $? -eq 1 ]
then
	Slash="~"
	AbsolutePath="${PWD:${#HOME}+1}/" #delete 'home/$USER/'
else	#equal 2
	Slash="/"
 	AbsolutePath="$PWD/"
fi
echod "$AbsolutePath"

#creation du chemin a afficher
DirectoriesList=$(tr '/' '\n' <<< "$AbsolutePath")
echod "$DirectoriesList"

OldIFS=$IFS
IFS=$'\n'

ArrayDirectory=($DirectoriesList)
echod "${ArrayDirectory[@]}"

checkFirstDir

for DirectoryName in "${ArrayDirectory[@]:1}"
do
    checkDirectory
    formatDirectoryName 
    Way+="/$DirectoryNameFormated"
done

IFS=$OldIFS

echo "$Slash$Way"